---
apiVersion: v1
kind: Namespace
metadata:
  name: zabbix
---
apiVersion: v1
kind: Secret
metadata:
  name: zbx-secrets
  namespace: zabbix
type: Opaque
data:
# password should be base64 encoded
  mysql-password: M1Q5UlJ0N1RmWkFwbXhzeg==
