# Deployment:
#  kubectl create -f create.yaml
#  cat create.yaml | ssh diggya.me kubectl create -f -
#
# Docker container: https://hub.docker.com/_/nextcloud
#
# container -> pvc -> pv
---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
#  namespace: nextcloud
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gluster-nxc
  namespace: nextcloud
subsets:
  - addresses:
    - ip: 10.8.0.7
    ports:
    - port: 3803
  - addresses:
    - ip: 10.8.0.8
    ports:
    - port: 3803
  - addresses:
    - ip: 10.8.0.1
    ports:
    - port: 3803
---
apiVersion: v1
kind: Service
metadata:
  name: gluster-nxc
  namespace: nextcloud
spec:
  ports:
  - port: 3803
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  labels:
    app: nextcloud
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 9Gi
  storageClassName: storage-local
  selector:
    matchLabels:
      app: "nextcloud"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
#      nodeSelector:
#        node-role: master
      volumes:
        - name: nextcloud-data
          glusterfs: # use glusterfs as storage
            endpoints: gluster-nxc
            path: nextcloud
        - name: nextcloud-www
          persistentVolumeClaim:
            claimName: nextcloud-pvc
      containers:
        - name: nextcloud
          image: nextcloud
          volumeMounts:
            - name: nextcloud-www
              mountPath: "/var/www/html"
            - name: nextcloud-data
              mountPath: "/var/www/html/data"
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: 10.8.0.1
            - name: MYSQL_DATABASE
              value: nxc
            - name: MYSQL_USER
              value: nxc
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nxc-secrets
                  key: mysql-password
            - name: NEXTCLOUD_ADMIN_USER
              value: admin
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nxc-secrets
                  key: admin-password
            - name: TRUSTED_PROXIES
              value: "10.* 192.168.*"
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "cloud.diggya.me nextcloud.diggya.me 10.* 192.*"
            - name: OVERWRITEHOST
              value: "cloud.diggya.me"
            - name: OVERWRITEPROTOCOL
              value: "https"
            - name: OVERWRITEWEBROOT
              value: "/"
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    app: nextcloud
  namespace: nextcloud
spec:
  type: NodePort
  selector:
    app: nextcloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
      nodePort: 30181
