---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels:
    app: nextcloud
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-local
  local:
    path: /var/www/nextcloud
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - diggya-core
          - radeon
