---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
  labels:
    app: nextcloud
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /opt/nfs/nextcloud
    server: 10.8.0.1
