# Deployment:
#  kubectl create -f pma.yaml
#
# Installation explained: https://www.serverlab.ca/tutorials/containers/kubernetes/deploy-phpmyadmin-to-kubernetes-to-manage-mysql-pods/
#
# Docker container: https://hub.docker.com/r/phpmyadmin/phpmyadmin/
#

#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: mysql-secrets
#type: Opaque
#data:
## password should be base64 encoded
#  root-password: c3VwZXItc2VjcmV0LXBhc3N3b3Jk
---
apiVersion: v1
kind: Namespace
metadata:
  name: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
  namespace: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_ABSOLUTE_URI
              value: "https://diggya.me/pma/"
            - name: PMA_HOSTS
              value: "10.8.0.1,10.8.0.7"
            - name: PMA_PORT
              value: "3306"
#            - name: MYSQL_ROOT_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-secrets
#                  key: root-password
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: phpmyadmin
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
      nodePort: 30180
